name: Build Wheels for MacOS

on:
  release:
    types:
      - created

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python3 -m pip install pytest wheel --upgrade pip

      - name: Install prereqs
        run: bash src/tools/install_pg_mac.sh ${{ github.ref }}

      - name: Build wheels
        run: python3 setup.py bdist_wheel --dist-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist